<a href="https://colab.research.google.com/github/RivrSantos/Analise-Machine-Learning/blob/main/Analise_Exploratoria_Modulo_16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget -q <<  https://raw.githubusercontent.com/andre-marcos-perez/ebac-course- utils/main/dataset/deliveries.json EOF \-O deliveries.json

In [11]:
import json

with open('/content/deliveries.json', mode= 'r', encoding= 'utf8') as file:
  data= json.load(file)

In [46]:
len(data)

199

In [13]:
example= data[0]

In [14]:
print(example.keys())

dict_keys(['name', 'region', 'origin', 'vehicle_capacity', 'deliveries'])

In [15]:
example['name']

'cvrp-2-df-33'

In [16]:
example['region']

'df-2'

In [18]:
example['origin']['lat']

-15.83814451122274

In [19]:
example['origin']['lng']

-48.05498915846707

In [20]:
example['vehicle_capacity']

180

In [22]:
example['deliveries'][0]['point']['lat']

-15.848929154862294

In [23]:
import pandas as pd

In [24]:
deliveries_df= pd.DataFrame(data)

In [25]:
deliveries_df.head()

,name,region,origin,vehicle_capacity,deliveries
0,cvrp-2-df-33,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': '313483a19d2f8d65cd5024c8d215cfbd', 'p..."
1,cvrp-2-df-73,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': 'bf3fc630b1c29601a4caf1bdd474b85', 'po..."
2,cvrp-2-df-20,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': 'b30f1145a2ba4e0b9ac0162b68d045c3', 'p..."
3,cvrp-1-df-71,df-1,"{'lng': -47.89366206897872, 'lat': -15.8051175...",180,"[{'id': 'be3ed547394196c12c7c27c89ac74ed6', 'p..."
4,cvrp-2-df-87,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': 'a6328fb4dc0654eb28a996a270b0f6e4', 'p..."

Repare que a coluna origin contém dados nested ou aninhados na estrutura do JSON. Vamos normalizar a coluna com uma operação conhecida como flatten ou achatamento, que transforma cada chave do JSON em uma nova coluna:

In [26]:
hub_origin_df = pd.json_normalize(deliveries_df["origin"])
hub_origin_df.head()

         lng        lat
0 -48.054989 -15.838145
1 -48.054989 -15.838145
2 -48.054989 -15.838145
3 -47.893662 -15.805118
4 -48.054989 -15.838145

Com o dados achatados, vamos juntá-los ao conjunto de dados principal:

In [27]:
deliveries_df = pd.merge(left=deliveries_df, right=hub_origin_df, how='inner', left_index=True, right_index=True)
deliveries_df.head()

,name,region,origin,vehicle_capacity,deliveries,lng,lat
0,cvrp-2-df-33,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': '313483a19d2f8d65cd5024c8d215cfbd', 'p...",-48.054989,-15.838145
1,cvrp-2-df-73,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': 'bf3fc630b1c29601a4caf1bdd474b85', 'po...",-48.054989,-15.838145
2,cvrp-2-df-20,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': 'b30f1145a2ba4e0b9ac0162b68d045c3', 'p...",-48.054989,-15.838145
3,cvrp-1-df-71,df-1,"{'lng': -47.89366206897872, 'lat': -15.8051175...",180,"[{'id': 'be3ed547394196c12c7c27c89ac74ed6', 'p...",-47.893662,-15.805118
4,cvrp-2-df-87,df-2,"{'lng': -48.05498915846707, 'lat': -15.8381445...",180,"[{'id': 'a6328fb4dc0654eb28a996a270b0f6e4', 'p...",-48.054989,-15.838145

In [28]:
deliveries_df = deliveries_df.drop("origin", axis=1)
deliveries_df = deliveries_df[ ["name", "region", "lng", "lat", "vehicle_capacity" , "deliveries"] ]
deliveries_df.head()

,name,region,lng,lat,vehicle_capacity,deliveries
0,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,"[{'id': '313483a19d2f8d65cd5024c8d215cfbd', 'p..."
1,cvrp-2-df-73,df-2,-48.054989,-15.838145,180,"[{'id': 'bf3fc630b1c29601a4caf1bdd474b85', 'po..."
2,cvrp-2-df-20,df-2,-48.054989,-15.838145,180,"[{'id': 'b30f1145a2ba4e0b9ac0162b68d045c3', 'p..."
3,cvrp-1-df-71,df-1,-47.893662,-15.805118,180,"[{'id': 'be3ed547394196c12c7c27c89ac74ed6', 'p..."
4,cvrp-2-df-87,df-2,-48.054989,-15.838145,180,"[{'id': 'a6328fb4dc0654eb28a996a270b0f6e4', 'p..."

In [29]:
deliveries_df.rename(columns={"lng": "hub_lng", "lat": "hub_lat"}, inplace=True)
deliveries_df.head()

,name,region,hub_lng,hub_lat,vehicle_capacity,deliveries
0,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,"[{'id': '313483a19d2f8d65cd5024c8d215cfbd', 'p..."
1,cvrp-2-df-73,df-2,-48.054989,-15.838145,180,"[{'id': 'bf3fc630b1c29601a4caf1bdd474b85', 'po..."
2,cvrp-2-df-20,df-2,-48.054989,-15.838145,180,"[{'id': 'b30f1145a2ba4e0b9ac0162b68d045c3', 'p..."
3,cvrp-1-df-71,df-1,-47.893662,-15.805118,180,"[{'id': 'be3ed547394196c12c7c27c89ac74ed6', 'p..."
4,cvrp-2-df-87,df-2,-48.054989,-15.838145,180,"[{'id': 'a6328fb4dc0654eb28a996a270b0f6e4', 'p..."

Coluna: deliveries Repare que a coluna deliveries contém dados nested ou aninhados na estrutura do JSON. Vamos normalizar a coluna com uma operação conhecida como explode ou explosão que transforma cada elemento da lista em uma linha. Por fim, faremos os flatten ou achatamento do resultado coluna:

In [30]:
deliveries_exploded_df = deliveries_df[["deliveries"]].explode("deliveries")
deliveries_exploded_df.head()

                                          deliveries
0  {'id': '313483a19d2f8d65cd5024c8d215cfbd', 'po...
0  {'id': '320c94b17aa685c939b3f3244c3099de', 'po...
0  {'id': '3663b42f4b8decb33059febaba46d5c8', 'po...
0  {'id': 'e11ab58363c38d6abc90d5fba87b7d7', 'poi...
0  {'id': '54cb45b7bbbd4e34e7150900f92d7f4b', 'po...

In [31]:
deliveries_normalized_df = pd.concat([ pd.DataFrame(deliveries_exploded_df ["deliveries"].apply( lambda record: record["size"]) ).rename(columns={"deliveries":  "delivery_size"}),
                                      pd.DataFrame(deliveries_exploded_df ["deliveries"].apply( lambda record: record["point"]["lng"]) ).rename(columns={"deliveries":  "delivery_lng"}),
                                      pd.DataFrame(deliveries_exploded_df ["deliveries"].apply( lambda record: record["point"]["lat"]) ).rename(columns={"deliveries":  "delivery_lat"}), ], axis= 1)

In [32]:
deliveries_normalized_df.head()

   delivery_size  delivery_lng  delivery_lat
0              9    -48.116189    -15.848929
0              2    -48.118195    -15.850772
0              1    -48.112483    -15.847871
0              2    -48.118023    -15.846471
0              7    -48.114898    -15.858055

Com o dados explodidos, vamos normalizá-los para combiná-los ao conjunto de dados principal:

In [33]:
len(deliveries_exploded_df)

636149

In [34]:
len(deliveries_df)

199

In [35]:
deliveries_df= deliveries_df.drop('deliveries', axis= 1)
deliveries_df= pd.merge(left=deliveries_df, right= deliveries_normalized_df,
                        how= 'right', left_index= True, right_index= True)

deliveries_df.reset_index(inplace= True, drop= True)
deliveries_df.head()

,name,region,hub_lng,hub_lat,vehicle_capacity,delivery_size,delivery_lng,delivery_lat
0,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,9,-48.116189,-15.848929
1,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,2,-48.118195,-15.850772
2,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,1,-48.112483,-15.847871
3,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,2,-48.118023,-15.846471
4,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,7,-48.114898,-15.858055

In [36]:
len(deliveries_df)

636149

Com os dados em mãos, vamos conhecer um pouco melhor a estrutura do nosso conjunto de dados.

In [37]:
deliveries_df.shape

(636149, 8)

In [38]:
deliveries_df.columns

Index(['name', 'region', 'hub_lng', 'hub_lat', 'vehicle_capacity',
       'delivery_size', 'delivery_lng', 'delivery_lat'],
      dtype='object')

In [39]:
deliveries_df.index

RangeIndex(start=0, stop=636149, step=1)

In [40]:
deliveries_df.info

<bound method DataFrame.info of                 name region    hub_lng    hub_lat  vehicle_capacity  \
0       cvrp-2-df-33   df-2 -48.054989 -15.838145               180
1       cvrp-2-df-33   df-2 -48.054989 -15.838145               180
2       cvrp-2-df-33   df-2 -48.054989 -15.838145               180
3       cvrp-2-df-33   df-2 -48.054989 -15.838145               180
4       cvrp-2-df-33   df-2 -48.054989 -15.838145               180
...              ...    ...        ...        ...               ...
636144  cvrp-2-df-62   df-2 -48.054989 -15.838145               180
636145  cvrp-2-df-62   df-2 -48.054989 -15.838145               180
636146  cvrp-2-df-62   df-2 -48.054989 -15.838145               180
636147  cvrp-2-df-62   df-2 -48.054989 -15.838145               180
636148  cvrp-2-df-62   df-2 -48.054989 -15.838145               180

        delivery_size  delivery_lng  delivery_lat
0                   9    -48.116189    -15.848929
1                   2    -48.118195    -15.850772
2                   1    -48.112483    -15.847871
3                   2    -48.118023    -15.846471
4                   7    -48.114898    -15.858055
...               ...           ...           ...
636144              8    -48.064269    -15.997694
636145              4    -48.065176    -16.003597
636146              9    -48.065841    -16.003808
636147              1    -48.062327    -16.001568
636148              9    -48.059420    -16.009234

[636149 rows x 8 columns]>

In [41]:
deliveries_df.head(n=5)

,name,region,hub_lng,hub_lat,vehicle_capacity,delivery_size,delivery_lng,delivery_lat
0,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,9,-48.116189,-15.848929
1,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,2,-48.118195,-15.850772
2,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,1,-48.112483,-15.847871
3,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,2,-48.118023,-15.846471
4,cvrp-2-df-33,df-2,-48.054989,-15.838145,180,7,-48.114898,-15.858055

Colunas e seus respectivos tipos de dados.

In [42]:
deliveries_df.dtypes

name                 object
region               object
hub_lng             float64
hub_lat             float64
vehicle_capacity      int64
delivery_size         int64
delivery_lng        float64
delivery_lat        float64
dtype: object

Atributos categóricos.

In [43]:
deliveries_df.select_dtypes("object").describe().transpose()

         count unique           top    freq
name    636149    199  cvrp-1-df-87    5636
region  636149      3          df-1  304708

from matplotlib import pyplot as plt
import seaborn as sns
_df_0.groupby('unique').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_1.groupby('top').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
_df_2.groupby('freq').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['top'].value_counts()
    for x_label, grp in _df_3.groupby('unique')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('unique')
_ = plt.ylabel('top')

from matplotlib import pyplot as plt
import seaborn as sns
import pandas as pd
plt.subplots(figsize=(8, 8))
df_2dhist = pd.DataFrame({
    x_label: grp['freq'].value_counts()
    for x_label, grp in _df_4.groupby('top')
})
sns.heatmap(df_2dhist, cmap='viridis')
plt.xlabel('top')
_ = plt.ylabel('freq')

Atributos numéricos

In [44]:
deliveries_df.drop( ["name", "region"], axis=1 ).select_dtypes('int64').describe().transpose()

,count,mean,std,min,25%,50%,75%,max
vehicle_capacity,636149.0,180.000000,0.000000,180.0,180.0,180.0,180.0,180.0
delivery_size,636149.0,5.512111,2.874557,1.0,3.0,6.0,8.0,10.0

Dados faltantes podem ser:

.  Vazios ("" ) ;

.  Nulos (None) ;

.  Não disponíveis ou aplicaveis ( na , NA , etc.);

.  Não numérico ( nan , NaN , NAN , etc).

Podemos verificar quais colunas possuem dados faltantes.

In [45]:
deliveries_df.isna().any()

name                False
region              False
hub_lng             False
hub_lat             False
vehicle_capacity    False
delivery_size       False
delivery_lng        False
delivery_lat        False
dtype: bool